# Jekyll Configuration File

title: CYK-Algorithmus von Endrullis
author: Aahash Sundararuban
email: Aahash.Sundararuban@campus.lmu.de
description: "Hier wird das Thema Cocke-Younger-Kasami-Algorithmus von Endrullis behandelt."
baseurl: "/cyk-algorithm-endrullis" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
exclude:
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
